### ISSUE TITLE
Sort result of users and other info commands

### ISSUE THREAD

**Issue by peyloride** [egegunes/redmine-cli#3]
For example users command returns users in no order, they should ordered by id or name.

**Comment by peyloride** [comment]
How should results be, ordered by name or ID? @egegunes

**Comment by egegunes** [comment]
IMO, ID is a better option for default but maybe we can let the user choose with an option like `--sort name`?

**Comment by peyloride** [comment]
ID is better on first sight but then I think as a normal user and what I want is just find my mate's name or projects name easily. If results are sorted by name, it would be easier to find.

Sort by an argument is good idea but I don't know is it good idea for 1.0 or not. Maybe we can think about it later.

**Comment by egegunes** [comment]
OK then let's sort by name and see how it goes. Once we have sorting functionality, it should be easy to switch between name and ID.
