### ISSUE TITLE
422 error when creating issue

### ISSUE THREAD

**Issue by hlobit** [egegunes/redmine-cli#33]
Seems like something introduced a regression, I may investigate later, but here is the issue.

### 1.1.8
```
$ redmine create --project 1146 --subject 'Fix company settings'
Status: ...
```

### 1.2.0
```
$ redmine create --project 1146 --subject 'Fix company settings'
Fatal: 422 Client Error: Unprocessable Entity for url: https://projects.mine.com/issues.json
```

**Comment by egegunes** [comment]
Hey Hubert, thank you for pointing out this bug. `project`, `status`, `tracker` and `priority` is required for creating an issue. Before 1.2.0 it was prompting for value if user left out any of these but this feature was blocking creating aliases for `create` command. With 1.3.0 I made this options required, not it'll force you to define all before sending the request.
